baseURL: "https://faithstory.info/"
title: "Apiporn Simapornchai (Faith)"
theme: "PaperMod"

pagination:
  pagerSize: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: false

googleAnalytics: "G-YLY454BM9Z"

minify:
  disableXML: true

languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: About
          url: "about/"
          weight: 1
        - name: Careers
          url: "careers/"
          weight: 2
        - name: Search
          url: "search/"
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  posts: "/:section/:year/:month/:slugorfilename/"

params:
  env: production
  description: "Apiporn Simapornchai"
  author: "Apiporn Simapornchai"

  assets:
    disableFingerprinting: true

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocSide: left

  profileMode:
    enabled: true
    title: "Apiporn Simapornchai (Faith)"
    subtitle: "Chief of Technology Officer | Lecturer | Advisors"

  socialIcons:
    - name: github
      url: "https://github.com/faithinyous"
    - name: linkedin
      url: "https://www.linkedin.com/in/faithinyou/"
    - name: email
      url: "mailto:apiporn.sima@gmail.com"
    - name: RsS
      url: "index.xml"

  # Recommended PaperMod options (optional)
  editPost:
    URL: "https://github.com/faithinyous/faithstory-hugo/edit/main/content/"
    Text: "Suggest Changes"
    appendFilePath: true

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
